# Generated by Django 4.2.20 on 2025-03-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEmotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=255)),
                ('happiness', models.FloatField(default=0.0)),
                ('sadness', models.FloatField(default=0.0)),
                ('anger', models.FloatField(default=0.0)),
                ('surprise', models.FloatField(default=0.0)),
                ('disgust', models.FloatField(default=0.0)),
                ('fear', models.FloatField(default=0.0)),
                ('neutral', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
