# Generated by Django 4.2.20 on 2025-03-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeremotion',
            name='analysis_feedback',
            field=models.CharField(default='無分析建議', max_length=255),
        ),
        migrations.AddField(
            model_name='customeremotion',
            name='dominant_emotion',
            field=models.CharField(default='無分析建議', max_length=50),
        ),
        migrations.AddField(
            model_name='customeremotion',
            name='emotion_data',
            field=models.JSONField(default=0.0),
        ),
    ]
