# Generated by Django 4.2.20 on 2025-03-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_detection', '0002_customeremotion_analysis_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeremotion',
            name='analysis_feedback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customeremotion',
            name='dominant_emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
