# Generated by Django 4.2.20 on 2025-04-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_detection', '0003_alter_customeremotion_analysis_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeremotion',
            name='analysis_feedback',
        ),
        migrations.RemoveField(
            model_name='customeremotion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customeremotion',
            name='dominant_emotion',
        ),
        migrations.AddField(
            model_name='customeremotion',
            name='customer_id',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='customeremotion',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_faces/'),
        ),
        migrations.AlterField(
            model_name='customeremotion',
            name='emotion_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customeremotion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
