# Generated by Django 4.2.20 on 2025-04-22 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_detection', '0004_remove_customeremotion_analysis_feedback_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
        migrations.AddField(
            model_name='customeremotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
