# Generated by Django 4.2.20 on 2025-12-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_detection', '0008_customeremotion_au01_customeremotion_au02_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionrecord',
            name='au_signature',
            field=models.JSONField(default=dict),
        ),
    ]
